# This file is overwritten by one in alphagov-deployment at deploy time
development:
  clients:
    default:
      hosts:
        - localhost
      database: govuk_content_development
  options:
    use_activesupport_time_zone: true
    belongs_to_required_by_default: false

test:
  clients:
    default:
      hosts:
        - localhost
      database: govuk_content_publisher_test
      options:
        read:
          mode: :primary
        max_pool_size: 1
  options:
    use_activesupport_time_zone: true
    belongs_to_required_by_default: false

# set these environment variables on your prod server
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
  options:
    use_activesupport_time_zone: true
    belongs_to_required_by_default: false
